### PR TITLE
post: Text and files for PCB de-layer teardown

### PR DESCRIPTION
**Pull request by kbembedded**

### CODE REVIEW

**Review by ShortTie — COMMENTED** [review]
Skimmed the text and it looks good. Need to get a setup to clone the repo and look at the pictures.

**Comment by kbembedded** [comment]
@ShortTie If you open the post in github web, it correctly renders the markdown, e.g.:

https://github.com/DCHHV/dchhv.github.io/blob/pcb_de-layer_writeup/_posts/2020-01-25-pcb-teardown-display.md

**Review by skyrian — APPROVED** [review]
Edited. Grammatically, looks good. Reads well, very instructional.

**Comment by kbembedded** [comment]
If there are no further comments, then I'm gonna merge this back in in a day or so.

**Pull request merged**
