### PR TITLE
dc30 markdown sched generated from the hhv admin scipts

### PR DESCRIPTION
**Pull request by BenGardiner**

### CODE REVIEW

**Comment by BenGardiner** [comment]
@ShortTie would you like the schedule posted?

**Comment by ShortTie** [comment]
Sure! Just been wrapped up with other things. Am trying to work the time in
to catch up this week.

**Comment by kbembedded** [comment]
Sorry, I'm just getting to this. I've been... overloaded...

The schedule itself doesn't render properly. If you check it out here: https://github.com/DCHHV/dchhv.github.io/blob/df730746f154ed6da0fa4ae575b6cc916c60fb2f/schedule/schedule.md

You can see the times and links are all on a single line. I'd suggest making them a table as was done in past years, or bullet points. Otherwise I think double spacing them in the .md file should just put each one their own line.

**Comment by ShortTie** [comment]
Added the table formatting.

**Comment by BenGardiner** [comment]
Nice. I think tie fixed it

**Pull request merged**
