### PR TITLE
update CFP for safe-mode

### PR DESCRIPTION
**Pull request by BenGardiner**

### CODE REVIEW

**Review by kbembedded — COMMENTED** [review]
Would suggest s/safe-mode/DEF CON Safe Mode/ to match their naming. Would also suggest turning that text in to a link to the defcon safemode page: https://www.defcon.org/html/defcon-safemode/dc-safemode-index.html (you'd have to look at another page for the MD syntax for jekyll, I can't recall off the top of my head).

**Comment by BenGardiner** [comment]
good notes, @kbembedded . all set.

**Comment by mediumrehr** [comment]
i think it looks great. if you want nitpicky edits, i'd change the line "This year more than others we are seeking anything and everything related to making your own use that is hands-on." to "This year, more than others, we are seeking anything and everything related to _Make Your Own Use_ that is hands-on." to address a grammatical thing and highlight our tagline better. either way, your addition gets the point across. 🤘

**Review by kbembedded — APPROVED** [review]
Looks good to me, I think this gets the message across well enough. Barring the suggestions from @mediumrehr I'm happy with the current edits.

I'm indifferent about @mediumrehr's suggestion, I don't think we focus on taglining "Make Your Own Use" in many places but there are riffs on it in postings and articles. If you feel like making another change, go for it!

**Pull request merged**
