### PR TITLE
Badgelife

### PR DESCRIPTION
**Pull request by devoopes**

### CODE REVIEW

**Review by BenGardiner — APPROVED** [review]

**Comment by kbembedded** [comment]
Just as a note for the future.

Changes were requested in a private channel in our Discord about a week after this was originally opened. I'll leave this PR open for the time being. Once we start posting DC32's schedule, hopefully sooner than a few weeks before con, I'd be happy to revisit this.

**Comment by devoopes** [comment]
@BenGardiner Looks like my PR got overwritten. May I please have write access on this repo to amend it or do I need to file another PR?

**Comment by kbembedded** [comment]
> Looks like my PR got overwritten. May I please have write access on this repo to amend it or do I need to file another PR?

As I noted in my comment. I requested changes in Discord which you acknowledged and then provided no change. The PR was not overwritten, it was never merged. As I said in my comment, if you update this PR with the requested changes, I'd be happy to merge.

**Comment by devoopes** [comment]
Per your comments in discord, you said you would merge. 

> okay, so, I've opened the poll results, go click the same link to see yourself. Overwhelmingly "yes." So, lets get that PR merged.

> If anyone has feedback on the PR or potential change requests, lets talk.

> <@355162483738017794> First, I would like to give you some options on how I want to see this play out. You mentioned being the point of contact. If we keep that event on the site as its worded now; you, or someone working with you needs to be there the whole of con. Sure maybe come in an hour late and/or leave an hour early and/or go for lunch. But we need someone there to answer on behalf of badgelife/badgemakers most of our opening hours, and an idea of when you'll be back if you step away. I don't want to just shrug at people who were told by our website to go to this specific place to ask questions. The other option is treat it like a workshop. Schedule something once, twice, each day, where people can come in, find you/others, and get their questions answered. Thats what our workshop/discussion format is intended to be. Give me days and times and I'll put it on the schedule.

> The other change I would like to see is removing "HHV volunteers." Right now, the way the text is reads like its saying that badgelife isn't a part of the HHV, but that the HHV is now a part of badgelife. I would love to have our volunteers to be able to help and answer questions, but I can't make them learn a topic they arn't interested about. And if we're going to say, on our website, "come learn about a group that sells things," I want it to be clear who they need to talk to. And that person is the badgelife contact in the HHV/SSV and not a random HHV/SSV volunteer.

If I need to make changes around wording then I can do that for next year. But most of your request was around the event space and me being there, which I was.

**Comment by kbembedded** [comment]
Yes. See where I asked for changes? I want to get it merged, but, requested changes. Which you responded `I’ll make some wording changes. Give me a few days.` and `Thank you for the feedback.`

Please make the requested changes and I will merge.

**Comment by kbembedded** [comment]
@devoopes I pushed a small change. Is that acceptable to you? If so, then I'm good with the rest of the content and ready to merge.

**Comment by devoopes** [comment]
Thank you for doing this. It means a lot for the community

**Comment by kbembedded** [comment]
Merged, thanks for cooperating with me on the wording.

**Pull request merged**
